function returnProducts() {
  return [
    {
      id: 1,
      name: "Elegant Women's V-Neck Midi Dress",
      category: "dress",
      description:
        "Make a statement with our elegant women's V-neck midi dress. This beautifully crafted dress combines sophistication with comfort, making it perfect for any occasion. The V-neck design and midi length create a flattering silhouette, while the high-quality fabric ensures a comfortable fit. Available in a range of sizes from Small to Extra Large.",
      price: 45,
      color: "Navy Blue",
      sizes: ["S", "M", "L", "XL"],
      image: "https://images.example.com/womens-midi-dress.jpg",
    },
    {
      id: 2,
      name: "Premium Men's Cotton Blend Crew Neck T-Shirt",
      category: "shirt",
      description:
        "Experience ultimate comfort with our premium men's cotton blend crew neck t-shirt. Crafted from a blend of high-quality cotton and polyester, this shirt is designed to provide a soft, breathable, and durable wearing experience. Whether you're dressing up or keeping it casual, this versatile shirt is a wardrobe essential. Available in a range of sizes from Small to Extra Large.",
      price: 290,
      discountPrice: 250,
      color: "Black",
      sizes: ["S", "M", "L", "XL"],
      description2: "This is a masterpiece of a shirt. bla  la bla",
      image: "https://images.example.com/mens-t-shirt.jpg",
      allImages: [
        "https://images.example.com/mens-t-shirt.jpg",
        "https://images.example.com/mens-t-shirt-1.jpg",
        "https://images.example.com/mens-t-shirt-2.jpg",
        "https://images.example.com/mens-t-shirt-3.jpg",
      ],
      bestSeller: true,
      newArrival: true,
      searchQueries: ["tshirt", "black tshirt", "2 more search queries"],
    },
    {
      id: 3,
      name: "Luxurious Men's Faux Fur Lined Hoodie",
      category: "hoodie",
      description:
        "Stay warm and stylish with our luxurious men's faux fur lined hoodie. This hoodie is not only a fashion statement, but also a functional piece of outerwear. The soft faux fur lining provides ultimate coziness, while the kangaroo pocket adds a touch of convenience. Crafted for a comfortable and relaxed fit, this hoodie is perfect for chilly days. Available in a range of sizes from Small to Extra Large.",
      price: 55,
      color: "Charcoal Gray",
      sizes: ["S", "M", "L", "XL"],
      image: "https://images.example.com/mens-faux-fur-hoodie.jpg",
    },
    {
      id: 4,
      name: "Stylish Women's Faux Leather Jacket",
      category: "jacket",
      description:
        "Add a touch of edge to your wardrobe with our stylish women's faux leather jacket. Crafted from high-quality faux leather, this jacket is designed to provide both style and durability. The flattering cut and versatile design make it a must-have for any fashion-forward individual. Whether you're dressing up for a night out or adding an edge to your everyday look, this jacket has got you covered. Available in a range of sizes from Small to Extra Large.",
      price: 70,
      color: "Burgundy",
      sizes: ["S", "M", "L", "XL"],
      image: "https://images.example.com/womens-faux-leather-jacket.jpg",
    },
    {
      id: 5,
      name: "Classic Unisex Snapback Hat",
      category: "hat",
      description:
        "Complete your look with our classic unisex snapback hat. This hat is designed for style and comfort, featuring an adjustable strap for a custom fit and a flat brim for a modern touch. Whether you're heading out for a casual day or want to add a sporty edge to your outfit, this snapback hat is the perfect accessory. One size fits all.",
      price: 20,
      color: "Red",
      sizes: [],
      image: "https://images.example.com/classic-snapback-hat.jpg",
    },
    {
      id: 6,
      name: "Cozy Unisex Cable Knit Beanie",
      category: "hat",
      description:
        "Stay warm and stylish with our cozy unisex cable knit beanie. This beanie is knitted from soft acrylic yarn, providing warmth and comfort while looking effortlessly stylish. The cable knit pattern adds a touch of texture to your outfit, making it the perfect accessory for chilly days. One size fits all.",
      price: 18,
      color: "Olive Green",
      sizes: [],
      image: "https://images.example.com/cable-knit-beanie.jpg",
    },
    {
      id: 7,
      name: "UV-Protected Polarized Sunglasses",
      category: "accessory",
      description:
        "Protect your eyes from the sun in style with our UV-protected polarized sunglasses. These sunglasses feature high-quality polarized lenses that reduce glare and provide optimal clarity. The durable frame ensures long-lasting use, making them perfect for outdoor activities. Whether you're hitting the beach or going for a drive, these sunglasses are a must-have accessory.",
      price: 35,
      color: "Black",
      sizes: [],
      image: "https://images.example.com/polarized-sunglasses.jpg",
    },
    {
      id: 8,
      name: "Genuine Leather Bifold Wallet",
      category: "accessory",
      description:
        "Organize your essentials in style with our genuine leather bifold wallet. This wallet is made from high-quality leather and features multiple card slots, a bill compartment, and a coin pocket. The classic bifold design ensures a slim and compact profile, making it easy to carry in your pocket or bag. Elevate your everyday carry with this timeless accessory.",
      price: 50,
      color: "Brown",
      sizes: [],
      image: "https://images.example.com/leather-wallet.jpg",
    },
    {
      id: 9,
      name: "Striped Polo Shirt with Embroidered Logo",
      category: "shirt",
      description:
        "Elevate your casual look with our striped polo shirt featuring an embroidered logo. Crafted from breathable cotton pique, this shirt offers both comfort and style. The classic striped pattern and embroidered logo add a touch of sophistication to your outfit. Perfect for both casual Fridays at the office and weekend outings with friends.",
      price: 35,
      color: "Navy Blue/White",
      sizes: ["S", "M", "L", "XL"],
      image: "https://images.example.com/striped-polo-shirt.jpg",
    },
    {
      id: 10,
      name: "Water-Resistant Down-Filled Parka Jacket",
      category: "jacket",
      description:
        "Brave the elements in style with our water-resistant down-filled parka jacket. This jacket features a durable water-resistant shell, a cozy down filling, and a detachable hood for versatile wear. The multiple pockets provide ample storage space, while the adjustable drawstrings allow you to customize the fit. Whether you're facing a chilly city commute or a winter adventure, this parka has you covered.",
      price: 90,
      color: "Charcoal Gray",
      sizes: ["S", "M", "L", "XL"],
      image: "https://images.example.com/down-filled-parka-jacket.jpg",
    },
    {
      id: 11,
      name: "Classic Men's Plaid Flannel Shirt",
      category: "shirt",
      description:
        "Stay cozy and stylish with our classic men's plaid flannel shirt. Crafted from soft and breathable cotton, this shirt is perfect for layering or wearing on its own. The timeless plaid pattern adds a touch of rugged charm to your look. Ideal for both indoor and outdoor activities, this shirt is a versatile addition to your wardrobe.",
      price: 40,
      color: "Red/Black",
      sizes: ["S", "M", "L", "XL"],
      image: "https://images.example.com/mens-plaid-flannel-shirt.jpg",
    },
    {
      id: 12,
      name: "Elegant Women's A-Line Evening Gown",
      category: "dress",
      description:
        "Make a statement at your next formal event with our elegant women's A-line evening gown. This stunning gown features a flattering A-line silhouette and intricate beadwork for a touch of glamour. The high-quality fabric drapes beautifully, creating a sophisticated look that's sure to turn heads. Available in a range of sizes from Small to Extra Large.",
      price: 150,
      color: "Navy Blue",
      sizes: ["S", "M", "L", "XL"],
      image: "https://images.example.com/womens-evening-gown.jpg",
    },
    {
      id: 13,
      name: "Warm and Cozy Unisex Scarf",
      category: "accessory",
      description:
        "Stay warm and stylish with our warm and cozy unisex scarf. Made from a blend of soft acrylic and wool, this scarf provides ultimate warmth and comfort. The classic knit pattern adds a touch of texture to your outfit, making it the perfect accessory for chilly days. One size fits all.",
      price: 25,
      color: "Burgundy",
      sizes: [],
      image: "https://images.example.com/cozy-scarf.jpg",
    },
    {
      id: 14,
      name: "Men's Slim Fit Suit in Charcoal Gray",
      category: "suit",
      description:
        "Look sharp and sophisticated with our men's slim fit suit in charcoal gray. This suit is tailored to perfection, featuring a modern slim fit and high-quality fabric. Whether you're heading to the office or attending a formal event, this suit exudes confidence and style. Available in a range of sizes from Small to Extra Large.",
      price: 250,
      color: "Charcoal Gray",
      sizes: ["S", "M", "L", "XL"],
      image: "https://images.example.com/mens-charcoal-suit.jpg",
    },
    {
      id: 15,
      name: "Women's Lightweight Trench Coat",
      category: "jacket",
      description:
        "Add a touch of elegance to your outerwear collection with our women's lightweight trench coat. This coat features a classic double-breasted design and a waist belt for a flattering silhouette. The lightweight fabric makes it suitable for transitional weather. Whether you're dressing up for the office or a night out, this trench coat is a timeless choice.",
      price: 80,
      color: "Beige",
      sizes: ["S", "M", "L", "XL"],
      image: "https://images.example.com/womens-trench-coat.jpg",
    },
    {
      id: 16,
      name: "Casual Men's Chino Pants",
      category: "pants",
      description:
        "Stay comfortable and stylish with our casual men's chino pants. Made from a blend of cotton and elastane, these pants offer a comfortable fit with a slight stretch for ease of movement. The classic chino design makes them versatile for both casual and semi-formal occasions. Available in a range of sizes from 28 to 36.",
      price: 45,
      color: "Khaki",
      sizes: ["28", "30", "32", "34", "36"],
      image: "https://images.example.com/mens-chino-pants.jpg",
    },
    {
      id: 17,
      name: "Chic Women's Ankle Boots",
      category: "shoes",
      description:
        "Step out in style with our chic women's ankle boots. These boots feature a sleek design with a comfortable block heel for all-day wear. The versatile ankle height pairs perfectly with both dresses and jeans. Whether you're heading to the office or a night on the town, these boots are a fashionable choice.",
      price: 70,
      color: "Black",
      sizes: ["5", "6", "7", "8", "9"],
      image: "https://images.example.com/womens-ankle-boots.jpg",
    },
    {
      id: 18,
      name: "Classic Men's Oxford Dress Shoes",
      category: "shoes",
      description:
        "Complete your formal look with our classic men's Oxford dress shoes. Crafted from premium leather, these shoes exude sophistication and quality. The timeless Oxford design features a cap toe and lace-up closure for a polished finish. Whether you're heading to a business meeting or a special event, these shoes will elevate your style.",
      price: 100,
      color: "Brown",
      sizes: ["7", "8", "9", "10", "11"],
      image: "https://images.example.com/mens-oxford-shoes.jpg",
    },
    {
      id: 19,
      name: "Effortless Women's Maxi Skirt",
      category: "skirt",
      description:
        "Achieve a boho-chic look with our effortless women's maxi skirt. This skirt features a flowy design with a comfortable elastic waistband. The lightweight fabric drapes beautifully, creating a free-spirited and feminine look. Whether you're strolling on the beach or attending a summer festival, this maxi skirt is a versatile addition to your wardrobe.",
      price: 40,
      color: "Navy Blue",
      sizes: ["S", "M", "L", "XL"],
      image: "https://images.example.com/womens-maxi-skirt.jpg",
    },
    {
      id: 20,
      name: "Men's Classic Denim Jacket",
      category: "jacket",
      description:
        "Upgrade your casual style with our men's classic denim jacket. Crafted from high-quality denim, this jacket offers both style and durability. The timeless design features chest pockets and button closure. Whether you're layering it over a t-shirt or a hoodie, this denim jacket adds a rugged edge to your look.",
      price: 60,
      color: "Blue",
      sizes: ["S", "M", "L", "XL"],
      image: "https://images.example.com/mens-denim-jacket.jpg",
    },
    {
      id: 21,
      name: "Women's Faux Fur Trimmed Parka",
      category: "jacket",
      description:
        "Stay warm and stylish with our women's faux fur trimmed parka. This parka features a cozy faux fur trim around the hood and a water-resistant shell to protect you from the elements. The drawstring waist allows you to customize the fit, while the multiple pockets provide ample storage. Whether you're running errands or exploring the outdoors, this parka has you covered.",
      price: 90,
      color: "Olive Green",
      sizes: ["S", "M", "L", "XL"],
      image: "https://images.example.com/womens-fur-parka.jpg",
    },
    {
      id: 22,
      name: "Men's Classic Leather Belt",
      category: "accessory",
      description:
        "Complete your look with our men's classic leather belt. This belt is crafted from genuine leather for a timeless and durable accessory. The simple and versatile design makes it a perfect match for both casual and formal outfits. Available in a range of sizes from 32 to 40.",
      price: 30,
      color: "Black",
      sizes: ["32", "34", "36", "38", "40"],
      image: "https://images.example.com/mens-leather-belt.jpg",
    },
    {
      id: 23,
      name: "Stylish Women's Wool Blend Coat",
      category: "coat",
      description:
        "Elevate your winter wardrobe with our stylish women's wool blend coat. This coat features a tailored fit and is crafted from a blend of wool and polyester for warmth and durability. The classic design is versatile for both formal and casual occasions. Whether you're heading to the office or out for a night on the town, this coat will keep you looking chic and cozy.",
      price: 120,
      color: "Camel",
      sizes: ["S", "M", "L", "XL"],
      image: "https://images.example.com/womens-wool-coat.jpg",
    },
    {
      id: 24,
      name: "Casual Men's Sneakers",
      category: "shoes",
      description:
        "Step up your casual footwear game with our men's casual sneakers. These sneakers feature a comfortable cushioned sole and a sleek design for everyday wear. Whether you're running errands or meeting up with friends, these sneakers provide both style and comfort.",
      price: 50,
      color: "White",
      sizes: ["7", "8", "9", "10", "11"],
      image: "https://images.example.com/mens-casual-sneakers.jpg",
    },
    {
      id: 25,
      name: "Classic Women's Leather Gloves",
      category: "accessory",
      description:
        "Stay warm and stylish with our classic women's leather gloves. Crafted from genuine leather, these gloves provide both style and durability. The soft lining adds an extra layer of warmth, making them perfect for chilly days. The classic design complements any winter outfit.",
      price: 35,
      color: "Black",
      sizes: ["S", "M", "L"],
      image: "https://images.example.com/womens-leather-gloves.jpg",
    },
    {
      id: 26,
      name: "Men's Lightweight Bomber Jacket",
      category: "jacket",
      description:
        "Add a touch of urban style to your wardrobe with our men's lightweight bomber jacket. This jacket features a sleek design with ribbed cuffs and a zip front closure. The lightweight fabric makes it ideal for transitional weather. Whether you're heading out for a night on the town or a casual day out, this bomber jacket is a versatile choice.",
      price: 70,
      color: "Navy Blue",
      sizes: ["S", "M", "L", "XL"],
      image: "https://images.example.com/mens-bomber-jacket.jpg",
    },
    {
      id: 27,
      name: "Elegant Women's Lace Cocktail Dress",
      category: "dress",
      description:
        "Make a statement at your next special occasion with our elegant women's lace cocktail dress. This dress features intricate lace detailing and a flattering A-line silhouette. The high-quality fabric provides both comfort and style. Whether you're attending a wedding or a formal event, this cocktail dress is sure to impress.",
      price: 80,
      color: "Burgundy",
      sizes: ["S", "M", "L", "XL"],
      image: "https://images.example.com/womens-lace-cocktail-dress.jpg",
    },
    {
      id: 28,
      name: "Men's Classic Cotton Polo Shirt",
      category: "shirt",
      description:
        "Upgrade your casual wardrobe with our men's classic cotton polo shirt. This shirt is crafted from high-quality cotton pique for a comfortable and breathable fit. The classic polo design features a ribbed collar and button placket. Whether you're headed to the golf course or a casual day out, this polo shirt is a timeless choice.",
      price: 35,
      color: "Navy Blue",
      sizes: ["S", "M", "L", "XL"],
      image: "https://images.example.com/mens-classic-polo-shirt.jpg",
    },
    {
      id: 29,
      name: "Women's Quilted Puffer Jacket",
      category: "jacket",
      description:
        "Stay cozy and stylish with our women's quilted puffer jacket. This jacket features a quilted design for extra insulation and a faux fur trimmed hood for added warmth. The zip front closure and multiple pockets make it practical for everyday wear. Whether you're running errands or heading out for a winter adventure, this puffer jacket has you covered.",
      price: 85,
      color: "Black",
      sizes: ["S", "M", "L", "XL"],
      image: "https://images.example.com/womens-quilted-puffer-jacket.jpg",
    },
    {
      id: 30,
      name: "Casual Men's Slim Fit Chinos",
      category: "pants",
      description:
        "Elevate your casual look with our casual men's slim fit chinos. These chinos are tailored for a modern slim fit and crafted from a blend of cotton and elastane for a comfortable stretch. The versatile design makes them suitable for both casual and semi-formal occasions. Available in a range of sizes from 28 to 36.",
      price: 50,
      color: "Olive Green",
      sizes: ["28", "30", "32", "34", "36"],
      image: "https://images.example.com/mens-slim-fit-chinos.jpg",
    },
  ];
}

export default returnProducts;
